# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.define "leo-broker" do |vm1|
    vm1.vm.box = "centos/7"
    vm1.vm.hostname = 'leo-broker'
    #vm1.vm.network "forwarded_port", id: "ssh", host: 1338, guest: 2222
    vm1.vm.network "forwarded_port", id: "http", host: 8080, guest: 80
    vm1.vm.network "forwarded_port", id: "https", host: 8443, guest: 443

    config.vm.provision "shell", privileged: true, path: "setup_leo.sh"
  end

  config.vm.provider :libvirt do |libvirt|
      libvirt.cpus = 2
      libvirt.memory = 8192
  end

  config.vm.provider "virtualbox" do |vb|
      vb.cpus = 2
      vb.memory = 8192
  end

  config.ssh.username = "vagrant"
  #config.ssh.password = "vagrant"

end
